/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.footprint.lx.struts.action;

import java.sql.SQLException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.footprint.dao.IAdminDao;
import com.footprint.dao.entity.admin;
import com.footprint.dao.impl.AdminDAODbimpl;

/** 
 * MyEclipse Struts
 * Creation date: 07-31-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="error" path="/background/bgLogin.jsp"
 * @struts.action-forward name="ok" path="/background/index.jsp"
 */
public class AdminLoginAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String name = request.getParameter("name");
		String pwd = request.getParameter("pwd");
		IAdminDao adminDAO = new AdminDAODbimpl();
		try {
			if(adminDAO.findByNameAndPwd(name, pwd)){
				List<admin> admins = adminDAO.findAll();
				for (admin admin : admins) {
					System.out.println(admin.getName()+"***********");
					if(admin.getName().equals(name)){
						System.out.println(admin+"xxxxxxxxxxxx");
						HttpSession session = request.getSession();
						session.setAttribute("admin", admin);
					}
				}
				return mapping.findForward("ok");
				
			}
			request.setAttribute("tishi", "d");
			return mapping.findForward("error");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return null;
	}
}