/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.footprint.lx.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.footprint.dao.IBookInfoDao;
import com.footprint.dao.impl.BookInfoDAODbimpl;


public class DeleteBookInfoAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String id = (String) request.getParameter(("bookId"));
		IBookInfoDao bookInfoDAO = new BookInfoDAODbimpl();
		if(bookInfoDAO.delete(id)){
		return mapping.findForward("ok");
		}
		return null;
	}
}