/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.footprint.lx.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.footprint.dao.IUser_aDao;
import com.footprint.dao.IUser_bDao;
import com.footprint.dao.impl.User_aDAODbimpl;
import com.footprint.dao.impl.User_bDAODbimpl;

/** 
 * MyEclipse Struts
 * Creation date: 07-31-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="ok" path="/cusInfoJsp/cusList.jsp"
 */
public class DeleteuserAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int id = Integer.parseInt(request.getParameter("id"));
		IUser_aDao user_a = new User_aDAODbimpl();
		IUser_bDao user_b = new User_bDAODbimpl();
		user_a.delete(id);
		user_b.delete(id);
		return mapping.findForward("ok");
	}
}