/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.footprint.lx.struts.action;

import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.footprint.dao.IAdminDao;
import com.footprint.dao.entity.admin;
import com.footprint.dao.impl.AdminDAODbimpl;

/** 
 * MyEclipse Struts
 * Creation date: 08-01-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class FindOneAdminAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int adminId = Integer.parseInt(request.getParameter("adminId"));
		IAdminDao adminDAO = new AdminDAODbimpl();
		try {
			admin admin = adminDAO.findById(adminId);
			request.setAttribute("admin", admin);
			return mapping.findForward("ok");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}
}