/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.footprint.lx.struts.action;

import java.sql.SQLException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.footprint.dao.ISeekInfoDao;
import com.footprint.dao.entity.seekInfo;
import com.footprint.dao.impl.SeekInfoDAODbimpl;

/** 
 * MyEclipse Struts
 * Creation date: 07-31-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="ok" path="/seekBookJsp/seekBookList.jsp"
 */
public class FindSeekInfoAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ISeekInfoDao seekDAO =new  SeekInfoDAODbimpl();
		try {
			List<seekInfo> seeks = seekDAO.findAll();
			request.setAttribute("seeks", seeks);
			return mapping.findForward("ok");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}
}