/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.footprint.lx.struts.action;

import java.sql.SQLException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.footprint.dao.IOrderDetailDao;
import com.footprint.dao.IOrderMainDao;
import com.footprint.dao.entity.orderDetail;
import com.footprint.dao.entity.orderMain;
import com.footprint.dao.impl.OrderDetailDAODbimpl;
import com.footprint.dao.impl.OrderMainDAODbimpl;

/** 
 * MyEclipse Struts
 * Creation date: 07-30-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="ok" path="/orderFullFind.jsp"
 */
public class FindDetailOrderAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int oid = Integer.parseInt(request.getParameter("oid"));
		IOrderMainDao orderMainDAO = new OrderMainDAODbimpl();
		IOrderDetailDao orderDAO = new OrderDetailDAODbimpl();
		try {
			orderMain orderMain = orderMainDAO.findById(oid);
			List<orderDetail> orders = orderDAO.findByoId(oid);
			request.setAttribute("orders", orders);
			request.setAttribute("orderMain", orderMain);
			request.setAttribute("oid", oid);
			return mapping.findForward("ok");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return null;
	}
}