/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.footprint.lx.struts.action;

import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.footprint.dao.IUser_aDao;
import com.footprint.dao.entity.user_a;
import com.footprint.dao.impl.User_aDAODbimpl;

public class LoginAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession session = request.getSession();
		String name = request.getParameter("userName");
		String pwd = request.getParameter("pwd");
		IUser_aDao userDAO = new User_aDAODbimpl();
		try {
			user_a user = userDAO.findByNameAndPwd(name, pwd);
			System.out.println("  "+user);
			if(user.getCustomerName()!=null){
				session.setAttribute("user", user);
				request.setAttribute("msg", "用户登录成功");
				request.setAttribute("returnPath", "initIndex.do");
			}else{
				request.setAttribute("msg", "登录失败");
				request.setAttribute("returnPath", "denglu.jsp");
			}
			return mapping.findForward("ok");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}
}