/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.footprint.lx.struts.action;

import java.sql.SQLException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.footprint.dao.IBookInfoDao;
import com.footprint.dao.IBookTypeDao;
import com.footprint.dao.entity.BookInfo;
import com.footprint.dao.entity.BookType;
import com.footprint.dao.impl.BookInfoDAODbimpl;
import com.footprint.dao.impl.BookTypeDAODbimpl;
import com.footprint.lx.struts.fenye.SplitPage;


public class SaveBookTypeAction extends Action {

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BookType type= new BookType();
		type.setBookTypeId(Integer.parseInt(request.getParameter("bookTypeId")));
		type.setBookTypeName((request.getParameter("bookTypeName")));
		type.setContext(request.getParameter("context"));
		type.setParentId(Integer.parseInt(request.getParameter("parentId")));
		type.setTypeIsDelete(1);
		IBookInfoDao bookInfoDAO = new BookInfoDAODbimpl();
		IBookTypeDao bookTypeDAO = new BookTypeDAODbimpl();
		SplitPage sp = new SplitPage();
		try {	
			List<BookType> Types = bookTypeDAO.findAll(sp);
			request.setAttribute("Types", Types);
			if(bookTypeDAO.addType(type)){
				return mapping.findForward("ok");
			}
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}
}