/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.footprint.lx.struts.action;

import java.sql.SQLException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.footprint.dao.IBookInfoDao;
import com.footprint.dao.IBookTypeDao;
import com.footprint.dao.entity.BookInfo;
import com.footprint.dao.entity.BookType;
import com.footprint.dao.impl.BookInfoDAODbimpl;
import com.footprint.dao.impl.BookTypeDAODbimpl;
import com.footprint.lx.struts.fenye.SplitPage;

public class SaveBookInfoAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BookInfo book = new BookInfo();
		book.setBookId(request.getParameter("bookId"));
		book.setAuthor(request.getParameter("author"));
		book.setBookName(request.getParameter("bookName"));
		book.setBookTypeId(Integer.parseInt(request.getParameter("tag3")));
		book.setContext(request.getParameter("context"));
		book.setPbName(request.getParameter("pbName"));
		book.setPrice(Integer.parseInt(request.getParameter("price")));
		book.setBookIsDelete(Integer.parseInt(request.getParameter("radio")));
		book.setSmallImg("smallImg");
		book.setBigImg("bigImg");
		book.setPbDate("2012-5-12");
		IBookInfoDao bookInfoDAO = new BookInfoDAODbimpl();
		IBookTypeDao bookTypeDAO = new BookTypeDAODbimpl();
		SplitPage sp = new SplitPage();
	
		try {	HttpSession session = request.getSession();
		
			String id = (String) session.getAttribute("id");
			System.out.println("******************"+id);
			if(id==null||id.equals("")){
			}else{bookInfoDAO.delete(id);}
			List<BookType> Types = bookTypeDAO.findAll(sp);
			request.setAttribute("Types", Types);
			if(bookInfoDAO.addBook(book)){
				return mapping.findForward("ok");
			}
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}
}