/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.footprint.lx.struts.action;

import java.sql.SQLException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.footprint.dao.IDiscussDao;
import com.footprint.dao.entity.user_a;
import com.footprint.dao.impl.DiscussDAODbimpl;

/** 
 * MyEclipse Struts
 * Creation date: 07-29-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class SaveDiscussAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int bookId = Integer.parseInt(request.getParameter("bookId"));
		String context = request.getParameter("context");
		IDiscussDao discussDAO = new DiscussDAODbimpl();
		HttpSession session = request.getSession();
		user_a user = (user_a) session.getAttribute("user");
		if(user==(null)){
			return mapping.findForward("error");
		}
		int uid = user.getCustomerId();
		try {
			discussDAO.addDiscuss(context, uid, bookId);
			request.setAttribute("path", "initIndex.do");
			request.setAttribute("msg", "增加书评成功");
		
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return mapping.findForward("ok");
	}
}