/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.footprint.lx.struts.action;

import java.sql.SQLException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.footprint.dao.IOrderMainDao;
import com.footprint.dao.entity.orderMain;
import com.footprint.dao.impl.OrderMainDAODbimpl;
import com.footprint.lx.struts.fenye.SplitPage;

/** 
 * MyEclipse Struts
 * Creation date: 08-01-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="ok" path="/itemList.jsp"
 */
public class ShowItemsAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		IOrderMainDao orderMain = new OrderMainDAODbimpl();
		SplitPage sp = new SplitPage();
		try {
			List<orderMain> orders  = orderMain.findAll(sp);
			request.setAttribute("orders", orders);
			return mapping.findForward("ok");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}
}