/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.footprint.lx.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.footprint.dao.IDiscussDao;
import com.footprint.dao.impl.DiscussDAODbimpl;

/** 
 * MyEclipse Struts
 * Creation date: 07-31-2013
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="ok" path="/discussList.jsp"
 */
public class UpdateDiscussAction extends Action {
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String disId = request.getParameter("id");
		String name = request.getParameter("status"+disId);
		int status = Integer.parseInt(name);
		int id = Integer.parseInt(disId);
		IDiscussDao discussDAO = new DiscussDAODbimpl();
		discussDAO.changeStates(id, status);
		return mapping.findForward("ok");
	}
}