/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.footprint.lx.struts.action;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.footprint.dao.IBookInfoDao;
import com.footprint.dao.IBookTypeDao;
import com.footprint.dao.entity.BookInfo;
import com.footprint.dao.entity.BookType;
import com.footprint.dao.impl.BookInfoDAODbimpl;
import com.footprint.dao.impl.BookTypeDAODbimpl;

public class UpdateBookInfoAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String id = (String) request.getParameter(("bookId"));
		HttpSession session = request.getSession();
		session.setAttribute("id", id);
		System.out.println(id);
		IBookInfoDao bookInfoDAO = new BookInfoDAODbimpl();
		IBookTypeDao bookTypeDAO = new BookTypeDAODbimpl();
		try {
			BookInfo book = bookInfoDAO.findById(id);
			int type3 = book.getBookTypeId();//目前书的类别ID
			BookType bookType = bookTypeDAO.findById(type3);//得到类别表中的类别对象
			int type2 = bookType.getParentId();//找到该书的父类别
			int type1 = bookTypeDAO.findById(type2).getParentId();//得到爷爷类别
			System.out.println(type1+"----------------"+type2+"----------------"+type3);
			request.setAttribute("types1",  bookTypeDAO.findByParentId(type1));
			request.setAttribute("types2",  bookTypeDAO.findByParentId(type2));
			request.setAttribute("type1", type1);
			request.setAttribute("type2", type2);
			request.setAttribute("type3", type3);
			List<BookType> types = new ArrayList<BookType>();
			types = bookTypeDAO.findByParentId(0);
			request.setAttribute("types", types);
			request.setAttribute("book", book);
			return mapping.findForward("ok");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		//bookInfoDAO.delete(id);
		
		return null;
	}
}